### ISSUE TITLE
IE11 doesn't work at all

### ISSUE THREAD

**Issue by syavych** [pete-rai/jquery-slidein#1]
Your plugin totally fails in IE11 :(

**Comment by pete-rai** [comment]
Oh boy - IE is a PITA. I only tested in Firefox and Chrome. I'll try and clear some time to take a look - I'll need to find a Windows machine first. Can you add any error messages or log at all?

**Comment by syavych** [comment]
Hi,
Yeah, I know that IE ..., don't use it all, but your plugin fits fine on one of my education project and there are still a lot of users of IE :(
Here's the console message:
SCRIPT1028: Expected identifier, string or number
jquery.slidein.js (268,51)
SCRIPT438: Object doesn't support property or method 'slidein'
58 (98,6)

Seems something wrong with this: { [this.options.dock]: move }

**Comment by MarkHeddaeus** [comment]
Quick workaround for this...probably not the best solution, but it works in IE11

Replace lines 268-275 
```
$(this._grab_handle).animate({ left: move }, this.options.speed, "linear");

$( this.element ).animate( { [this.options.dock]: move }, this.options.speed, "linear", function() {
    self._sliding = false;
    self._trigger( "slide", null, { open: self.options.open, dock: self.options.dock } );  // trigger to any "we slid" handlers
});
```


with a switch statement:
```
switch(this.options.dock) {
    case "left":
        $(this._grab_handle).animate({ left: move }, this.options.speed, "linear");

        $( this.element ).animate( { left: move }, this.options.speed, "linear", function() {
            self._sliding = false;
            self._trigger( "slide", null, { open: self.options.open, dock: self.options.dock } );  // trigger to any "we slid" handlers
        });

        break;
    case "top":
        $(this._grab_handle).animate({ top: move }, this.options.speed, "linear");

        $( this.element ).animate( { top: move }, this.options.speed, "linear", function() {
            self._sliding = false;
            self._trigger( "slide", null, { open: self.options.open, dock: self.options.dock } );  // trigger to any "we slid" handlers
        });

        break;
    case "right":
        $(this._grab_handle).animate({ right: move }, this.options.speed, "linear");

        $( this.element ).animate( { right: move }, this.options.speed, "linear", function() {
            self._sliding = false;
            self._trigger( "slide", null, { open: self.options.open, dock: self.options.dock } );  // trigger to any "we slid" handlers
        });

        break;
    case "bottom":
        $(this._grab_handle).animate({ bottom: move }, this.options.speed, "linear");

        $( this.element ).animate( { bottom: move }, this.options.speed, "linear", function() {
            self._sliding = false;
            self._trigger( "slide", null, { open: self.options.open, dock: self.options.dock } );  // trigger to any "we slid" handlers
        });

        break;
}
```

**Comment by pete-rai** [comment]
Great thanks for this Mark. So looks like IE does not support dynamic JSON labels. 

Let me analyze this and check in a solution to the trunk.

**Comment by pete-rai** [comment]
Well thanks to MarkHeddaeus I have checked in a fix for IE. 

I've now tested it as working in IE, Chrome, Firefox and Safari. 

I went with a more elegant fix than the workaround posted above. I set the properties object outside the call to animate using more usual JavaScript syntax. Seems you cannot dynamically set an object label in the IE JS engine. 

Ho hum, its all fixed now.
